#!/usr/bin/env python3
"""AI integration phase support — context retrieval, artifact writing, gate checks."""

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from scripts.db import connect, get_db_path
from scripts.state import get_phase, list_milestones, list_phases


# ── Context Retrieval ─────────────────────────────────────────────────────────


def get_ai_context(conn: sqlite3.Connection, phase_id: int | None = None) -> dict:
    """Return phase context needed to run ai-phase.

    If phase_id is None, finds the first phase in planned/planned_out status.
    Returns dict with keys: phase_id, phase_name, description, acceptance_criteria,
    tech_stack, phase_dir, slug, milestone_id.
    Returns {"error": "..."} if no suitable phase is found.
    """
    phase: dict | None = None

    if phase_id is not None:
        phase = get_phase(conn, phase_id)
        if phase is None:
            return {"error": f"Phase {phase_id} not found"}
    else:
        milestones = list_milestones(conn)
        active = [m for m in milestones if m.get("status") == "active"]
        search_order = active + [m for m in milestones if m not in active]
        for milestone in search_order:
            phases = list_phases(conn, milestone["id"])
            for p in phases:
                if p.get("status") in ("planned", "planned_out"):
                    phase = p
                    break
            if phase:
                break

    if phase is None:
        return {"error": "No planned or planned_out phase found. Run /meridian:plan first."}

    name_slug = phase["name"].lower().replace(" ", "-").replace("/", "-")
    seq = phase.get("sequence_number") or phase.get("id")
    slug = f"{seq:02d}-{name_slug}" if isinstance(seq, int) else name_slug

    project_row = conn.execute(
        "SELECT tech_stack FROM project WHERE id = 'default'"
    ).fetchone()
    tech_stack = (project_row["tech_stack"] if project_row else None) or "Not specified"

    criteria = phase.get("acceptance_criteria") or []
    if isinstance(criteria, str):
        try:
            criteria = json.loads(criteria)
        except (json.JSONDecodeError, ValueError):
            criteria = [criteria]

    return {
        "phase_id": phase["id"],
        "phase_name": phase["name"],
        "description": phase.get("description") or "",
        "acceptance_criteria": criteria,
        "tech_stack": tech_stack,
        "slug": slug,
        "phase_dir": f".planning/phases/{slug}",
        "milestone_id": phase.get("milestone_id"),
    }


# ── Artifact Checks ───────────────────────────────────────────────────────────


def check_ai_artifact(phase_dir: Path) -> bool:
    """Return True if a non-empty AI-SPEC.md exists in phase_dir."""
    path = Path(phase_dir) / "AI-SPEC.md"
    return path.is_file() and path.stat().st_size > 100


# ── Artifact Writing ──────────────────────────────────────────────────────────


def write_ai_spec_md(
    phase_dir: Path,
    phase_name: str,
    phase_id: int,
    domain: str,
    framework: str,
    eval_strategy: str,
) -> Path:
    """Write AI-SPEC.md artifact for a phase.

    Creates the phase artifact directory if it doesn't exist.
    Returns the path to the written AI-SPEC.md.
    """
    phase_dir = Path(phase_dir)
    phase_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    content = f"""# Phase {phase_id}: {phase_name} — AI Integration Spec

**Specced:** {now}
**Phase ID:** {phase_id}

## Domain & Problem Framing

{domain.strip()}

## Framework & Model Selection

{framework.strip()}

## Evaluation Strategy, Guardrails & Monitoring

{eval_strategy.strip()}

---

*Generated by /meridian:ai-phase*
"""
    out = phase_dir / "AI-SPEC.md"
    out.write_text(content, encoding="utf-8")
    return out


# ── Completion Marker ─────────────────────────────────────────────────────────


def mark_ai_complete(conn: sqlite3.Connection, phase_id: int) -> None:
    """Store AI spec completion timestamp in phase notes column."""
    now = datetime.now(timezone.utc).isoformat()
    existing = conn.execute(
        "SELECT notes FROM phase WHERE id = ?", (phase_id,)
    ).fetchone()
    existing_notes: dict = {}
    if existing and existing["notes"]:
        try:
            existing_notes = json.loads(existing["notes"])
        except (json.JSONDecodeError, ValueError):
            existing_notes = {}
    existing_notes["ai_spec_complete"] = True
    existing_notes["ai_spec_date"] = now
    conn.execute(
        "UPDATE phase SET notes = ? WHERE id = ?",
        (json.dumps(existing_notes), phase_id),
    )
    conn.commit()


def is_ai_complete(conn: sqlite3.Connection, phase_id: int) -> bool:
    """Return True if phase has been marked ai_spec_complete in DB."""
    row = conn.execute(
        "SELECT notes FROM phase WHERE id = ?", (phase_id,)
    ).fetchone()
    if not row or not row["notes"]:
        return False
    try:
        notes = json.loads(row["notes"])
        return bool(notes.get("ai_spec_complete"))
    except (json.JSONDecodeError, ValueError):
        return False


def get_ai_metadata(conn: sqlite3.Connection, phase_id: int) -> dict | None:
    """Return AI spec metadata from phase notes, or None if not complete."""
    row = conn.execute(
        "SELECT notes FROM phase WHERE id = ?", (phase_id,)
    ).fetchone()
    if not row or not row["notes"]:
        return None
    try:
        notes = json.loads(row["notes"])
        if not notes.get("ai_spec_complete"):
            return None
        return {"ai_spec_date": notes.get("ai_spec_date")}
    except (json.JSONDecodeError, ValueError):
        return None


# ── Gate Check ────────────────────────────────────────────────────────────────


def ai_gate(
    phase_dir: Path,
    conn: sqlite3.Connection | None = None,
    phase_id: int | None = None,
) -> dict:
    """Soft gate: check if AI spec is complete before plan/execute starts.

    Returns dict with: passed, warning, ai_spec_path.
    passed=True means AI-SPEC.md exists (proceed). passed=False is a soft warning.
    """
    artifact_ok = check_ai_artifact(phase_dir)

    if artifact_ok:
        return {
            "passed": True,
            "warning": None,
            "ai_spec_path": str(Path(phase_dir) / "AI-SPEC.md"),
        }

    return {
        "passed": False,
        "warning": (
            "AI-SPEC.md not found. Run /meridian:ai-phase to select a framework, "
            "design an eval strategy, and define guardrails before planning. "
            "Use --skip-ai to bypass (not recommended)."
        ),
        "ai_spec_path": None,
    }


# ── CLI Helper ────────────────────────────────────────────────────────────────


if __name__ == "__main__":
    import sys

    phase_id_arg = int(sys.argv[1]) if len(sys.argv) > 1 else None
    conn = connect(get_db_path("."))
    ctx = get_ai_context(conn, phase_id_arg)
    conn.close()
    print(json.dumps(ctx, indent=2, default=str))
