#!/usr/bin/env python3
"""Research phase support — context retrieval, artifact writing, completion marking."""

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from scripts.db import connect, get_db_path
from scripts.state import get_phase, list_phases, list_milestones


# ── Context Retrieval ─────────────────────────────────────────────────────────


def get_research_context(conn: sqlite3.Connection, phase_id: int | None = None) -> dict:
    """Return phase context needed to populate researcher prompts.

    If phase_id is None, finds the first phase in pending/planned_out status.

    Returns dict with keys: phase_id, phase_name, description, acceptance_criteria,
    tech_stack, phase_dir, slug, milestone_id.
    Returns {"error": "..."} if no suitable phase is found.
    """
    phase: dict | None = None

    if phase_id is not None:
        phase = get_phase(conn, phase_id)
        if phase is None:
            return {"error": f"Phase {phase_id} not found"}
    else:
        # Walk milestones to find first pending/planned_out phase
        milestones = list_milestones(conn)
        active = [m for m in milestones if m.get("status") == "active"]
        search_order = active + [m for m in milestones if m not in active]
        for milestone in search_order:
            phases = list_phases(conn, milestone["id"])
            for p in phases:
                if p.get("status") in ("pending", "planned_out"):
                    phase = p
                    break
            if phase:
                break

    if phase is None:
        return {"error": "No pending or planned phase found. Run /meridian:plan first."}

    # Build slug from phase name (matches artifact dir convention)
    name_slug = phase["name"].lower().replace(" ", "-").replace("/", "-")
    seq = phase.get("sequence_number") or phase.get("id")
    slug = f"{seq:02d}-{name_slug}" if isinstance(seq, int) else name_slug

    # Pull tech stack from project
    project_row = conn.execute(
        "SELECT tech_stack FROM project WHERE id = 'default'"
    ).fetchone()
    tech_stack = (project_row["tech_stack"] if project_row else None) or "Not specified"

    criteria = phase.get("acceptance_criteria") or []
    if isinstance(criteria, str):
        try:
            criteria = json.loads(criteria)
        except (json.JSONDecodeError, ValueError):
            criteria = [criteria]

    return {
        "phase_id": phase["id"],
        "phase_name": phase["name"],
        "description": phase.get("description") or "",
        "acceptance_criteria": criteria,
        "tech_stack": tech_stack,
        "slug": slug,
        "phase_dir": f".planning/phases/{slug}",
        "milestone_id": phase.get("milestone_id"),
    }


# ── Artifact Writing ──────────────────────────────────────────────────────────


def write_research_md(
    phase_dir: Path,
    phase_name: str,
    phase_id: int,
    domain: str,
    technical: str,
    competitive: str | None = None,
) -> Path:
    """Write RESEARCH.md artifact for a phase.

    Creates the phase artifact directory if it doesn't exist.
    Returns the path to the written RESEARCH.md.
    """
    phase_dir = Path(phase_dir)
    phase_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    competitive_section = ""
    if competitive and competitive.strip():
        competitive_section = f"""
## Competitive & Reference Analysis

{competitive.strip()}
"""

    content = f"""# Phase {phase_id}: {phase_name} — Research

**Researched:** {now}
**Phase ID:** {phase_id}

## Summary

See domain, technical, and competitive sections below.

## Domain & Business Context

{domain.strip()}
{competitive_section}
## Technical Implementation

{technical.strip()}

---

*Generated by /meridian:research-phase*
"""
    out = phase_dir / "RESEARCH.md"
    out.write_text(content, encoding="utf-8")
    return out


# ── Completion Marker ─────────────────────────────────────────────────────────


def mark_research_complete(conn: sqlite3.Connection, phase_id: int) -> None:
    """Store research completion timestamp in phase notes column."""
    now = datetime.now(timezone.utc).isoformat()
    existing = conn.execute(
        "SELECT notes FROM phase WHERE id = ?", (phase_id,)
    ).fetchone()
    existing_notes: dict = {}
    if existing and existing["notes"]:
        try:
            existing_notes = json.loads(existing["notes"])
        except (json.JSONDecodeError, ValueError):
            existing_notes = {}
    existing_notes["research_complete"] = True
    existing_notes["research_date"] = now
    conn.execute(
        "UPDATE phase SET notes = ? WHERE id = ?",
        (json.dumps(existing_notes), phase_id),
    )
    conn.commit()


def is_research_complete(conn: sqlite3.Connection, phase_id: int) -> bool:
    """Return True if phase has been marked research_complete in DB."""
    row = conn.execute(
        "SELECT notes FROM phase WHERE id = ?", (phase_id,)
    ).fetchone()
    if not row or not row["notes"]:
        return False
    try:
        notes = json.loads(row["notes"])
        return bool(notes.get("research_complete"))
    except (json.JSONDecodeError, ValueError):
        return False


# ── Gate Check ────────────────────────────────────────────────────────────────


def check_research_artifact(phase_dir: Path) -> bool:
    """Return True if a non-empty RESEARCH.md exists in phase_dir."""
    path = Path(phase_dir) / "RESEARCH.md"
    return path.is_file() and path.stat().st_size > 100


def research_gate(phase_dir: Path, conn: sqlite3.Connection | None = None, phase_id: int | None = None) -> dict:
    """Soft gate: check if research is complete before plan phase starts.

    Returns dict with: passed, warning, research_path.
    Passed=True means research exists (proceed). Passed=False is a soft warning.
    """
    artifact_ok = check_research_artifact(phase_dir)
    db_ok = False
    if conn is not None and phase_id is not None:
        db_ok = is_research_complete(conn, phase_id)

    if artifact_ok:
        return {
            "passed": True,
            "warning": None,
            "research_path": str(Path(phase_dir) / "RESEARCH.md"),
        }

    return {
        "passed": False,
        "warning": (
            "RESEARCH.md not found. Run /meridian:research-phase to investigate "
            "this phase before planning. Use --skip-research to bypass (not recommended)."
        ),
        "research_path": None,
    }


# ── CLI Helper ────────────────────────────────────────────────────────────────


if __name__ == "__main__":
    import sys

    phase_id_arg = int(sys.argv[1]) if len(sys.argv) > 1 else None
    conn = connect(get_db_path("."))
    ctx = get_research_context(conn, phase_id_arg)
    conn.close()
    print(json.dumps(ctx, indent=2, default=str))
